version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.2
  jira: circleci/jira@2.2.0
  allure: ayte/allure@0.1.3
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1-browsers
    working_directory: ~/repo
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            playwright install
      - run: mkdir -p test-reports
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pytest test_hotel_planisphere.py -v --alluredir=test-results/allure --junit-xml=test-results/results.xml --html=test-reports/report.html --self-contained-html
      - allure/report:
        results-path: test-results/allure
        target-path: allure-report
      - store_artifacts:
          path: allure-report
          destination: allure-report
      - store_test_results:
          path: test-results
      - jira/notify:
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
workflows:
  build-workflow:
    jobs:
      - build:
          context: $JIRA_WEBHOOK_URL
