version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10.1-browsers
    working_directory: ~/repo

jobs:
  build:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install allure-pytest

      - run:
          name: Run tests with Allure
          command: |
            . venv/bin/activate
            pytest test_hotel_planisphere.py --alluredir=allure-results

      - run:
          name: Install Allure Commandline
          command: |
            . venv/bin/activate
            npm install -g allure-commandline

      - run:
          name: Generate Allure Report with History
          command: |
            allure generate allure-results --clean

      - run:
          name: Install AWS CLI
          command: |
            . venv/bin/activate
            apt-get update
            apt-get install -y awscli

      - run:
          name: Configure AWS CLI
          command: |
            . venv/bin/activate
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region eu-central-1

      - run:
          name: Define Timestamp
          command: |
            echo 'export TIMESTAMP=$(date +%Y%m%d%H%M%S)' >> $BASH_ENV

      - run:
          name: Upload New Allure Report to S3
          command: |
            . venv/bin/activate
            UNIQUE_REPORT_DIR="build-$(echo $CIRCLE_BUILD_NUM)-${TIMESTAMP}"
            aws s3 sync ./allure-report s3://your-bucket/allure-reports/$UNIQUE_REPORT_DIR --acl public-read

      - run:
          name: Update Latest Report Reference
          command: |
            . venv/bin/activate
            aws s3 rm s3://your-bucket/allure-reports/latest --recursive
            aws s3 cp --recursive ./allure-report s3://your-bucket/allure-reports/latest/
            aws s3 cp --recursive ./allure-report/history s3://your-bucket/allure-reports/latest/history/

      - run:
          name: Display Allure Report URL
          command: |
            echo "Allure report is available at https://your-bucket.s3.eu-central-1.amazonaws.com/allure-reports/${UNIQUE_REPORT_DIR}/index.html" > allure-report-url.txt

      - store_artifacts:
          path: allure-report-url.txt
          destination: allure-report-url

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
