version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10.1-browsers
    working_directory: ~/repo

jobs:
  build:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install allure-pytest
            playwright install

      - run:
          name: Create allure results directory
          command: mkdir -p allure-results

      - run:
          name: Run tests with Allure
          command: |
            . venv/bin/activate
            pytest test_hotel_planisphere.py --alluredir=allure-results

      - run:
          name: Install Allure Commandline
          command: |
            . venv/bin/activate
            npm install allure-commandline

      - run:
          name: Generate Allure Report with History
          command: |
            npx allure generate allure-results --clean

      - run:
          name: Zip allure results
          command: |
            zip -r allure-results.zip allure-results

      - store_artifacts:
          path: allure-results.zip
          destination: allure-results

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
