version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.2
  jira: circleci/jira@2.2.0
  allure: ayte/allure@0.1.3
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1-browsers
    working_directory: ~/repo
    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            playwright install

      - run:
        name: Create required directories
        command: |
          mkdir -p test-results/allure

      - run:
          name: Run test
          command: |
            . venv/bin/activate
            pytest test_hotel_planisphere.py -v --alluredir=test-results/allure

      - allure/install:
        version: "2.13.1"

      - allure/report:
        results-path: test-results/allure
        target-path: allure-report
        artifact-path: Report/Allure

      - store_artifacts:
          path: allure-report
          destination: Report/Allure

      - store_test_results:
          path: test-results

      - jira/notify:
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>

workflows:
  build-workflow:
    jobs:
      - build:
          context: $JIRA_WEBHOOK_URL
